# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenge', '0002_auto_20170604_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
