# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenge', '0004_challengeattempt_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='earned_pts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
