# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenge', '0006_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
